{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ts",
    "module": "bindid",
    "version": "1.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "bindid-1.15.0.aar",
          "url": "bindid-1.15.0.aar",
          "size": 302411,
          "sha512": "0da1fe1955dd5d1206ad903e9e625d29170193f7feff1af0c5042c9b44a029d0a654c0212ab06fe75b7e37596daa040a269f1877880047720b04f97ffa6ed517",
          "sha256": "9ad92ad935eabb03fff23772862de247253f3aca842699f5d821a3241d359d10",
          "sha1": "5f9b0ad6219e7d2d16b5b1675cfcf7fd13c7ea46",
          "md5": "ac636c4ce8505b84b70463f306d55639"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.7.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-identity-credential",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "bindid-1.15.0.aar",
          "url": "bindid-1.15.0.aar",
          "size": 302411,
          "sha512": "0da1fe1955dd5d1206ad903e9e625d29170193f7feff1af0c5042c9b44a029d0a654c0212ab06fe75b7e37596daa040a269f1877880047720b04f97ffa6ed517",
          "sha256": "9ad92ad935eabb03fff23772862de247253f3aca842699f5d821a3241d359d10",
          "sha1": "5f9b0ad6219e7d2d16b5b1675cfcf7fd13c7ea46",
          "md5": "ac636c4ce8505b84b70463f306d55639"
        }
      ]
    }
  ]
}
